language: swift
osx_image: xcode11.2
rvm: 2.5.1

cache:
  cocoapods: true

install:
- bundle install -j5
- pod repo update
- pod install
- brew install jq

env:
  - SCHEME=iOSTests
  - SCHEME=tvOSTests
  - SCHEME=macOSTests

script:
  - bundle exec fastlane remote_httpbin
  - export DESTINATION="$(./scripts/destination.sh $SCHEME)"
  - xcrun simctl list
  - set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Tests.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" build test | xcpretty
